# Generated by Django 4.2.4 on 2023-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangulation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triangulation',
            name='body',
        ),
        migrations.RemoveField(
            model_name='triangulation',
            name='title',
        ),
        migrations.AddField(
            model_name='triangulation',
            name='N',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='triangulation',
            name='R',
            field=models.FloatField(default=7),
        ),
        migrations.AddField(
            model_name='triangulation',
            name='h',
            field=models.FloatField(default=16),
        ),
    ]
